FROM python:3.11-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /app

COPY pyproject.toml uv.lock ./
COPY cs336_basics/ ./cs336_basics/
COPY tokenizing_artifacts/ ./tokenizing_artifacts/

RUN uv sync --frozen

CMD ["uv", "run", "python"]
